; ==========================================
; AMBIENTE 1: Código em C (Arduino)
; ==========================================
[env:mega2560_versao_C]
platform = atmelavr
board = megaatmega2560
framework = arduino
; Compila apenas a pasta 'c' e ignora a 'assembly'
build_src_filter = +<c/> -<assembly/>

; ==========================================
; AMBIENTE 2: Código em Assembly Puro
; ==========================================
[env:mega2560_versao_Assembly]
platform = atmelavr
board = megaatmega2560
; Sem a linha 'framework = arduino' para ser bare-metal
; Compila apenas a pasta 'assembly' e ignora a 'c'
build_src_filter = +<assembly/> -<c/>