; Configuração base para não repetir código
[env]
platform = atmelavr
board = megaatmega2560

; Ambiente 1: Transmissor
[env:transmissor]
build_flags = -D IS_TRANSMISSOR
; upload_port = COM3  <-- (Opcional) Você pode fixar a porta de cada Arduino aqui depois

; Ambiente 2: Receptor
[env:receptor]
build_flags = -D IS_RECEPTOR
; upload_port = COM4  <-- (Opcional)