[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560

; Avisa o compilador que não vamos usar o framework do Arduino
; e que queremos compilar arquivos .S (Assembly) puros
build_flags = 
    -nostartfiles
