[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Force the internal board manifest to treat this as 4MB
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

; Use the specific 4MB partition table
board_build.partitions = default.csv
board_build.filesystem = littlefs
build_flags = 
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D BOARD_HAS_PSRAM=0  ; Ensure PSRAM isn't trying to initialize if not present

monitor_speed = 115200
